version: "3.9"

services:
  api_service:
    build: ./api_service
    ports:
      - "8000:8000"
    volumes:
      - ./api_service/logs:/app/logs
      - ./shared:/app/shared
    depends_on:
      - alert_service
      - influxdb

  alert_service:
    build: ./alert_service
    ports:
      - "8001:8001"
    volumes:
      - ./alert_service/logs:/app/logs
      - ./alert_service/error_reports:/app/error_reports
      - ./shared:/app/shared
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=logs
      - INFLUXDB_ADMIN_USER=admin
      # - INFLUXDB_ADMIN_PASSWORD=adminpass
    volumes:
      - ./influxdb:/var/lib/influxdb
      
  redis:
    image: redis:7

  worker:
    build: ./api_service
    command: celery -A celery_app worker --loglevel=info
    depends_on:
      - redis
      - alert_service
    volumes:
      - ./shared:/app/shared